import datetime
import os

def generate_automated_cti_report(incident_data):
    # Step 1: Folder creation logic
    if not os.path.exists("reports"):
        os.makedirs("reports")

    # Step 2 & 4: Variable Extraction (Logic base)
    host = incident_data.get('host', 'N/A')
    score = incident_data.get('score', 0)
    priority = incident_data.get('priority', 'UNKNOWN')
    findings = incident_data.get('findings', [])
    attacker_ip = incident_data.get('attacker_ip', 'N/A') 
    c2_domain = incident_data.get('c2_domain', 'N/A')

    recs = [
        f"Block malicious IP: {attacker_ip}",
        f"Reset comperomised credentials for {host}",
        f"Investigate affected host: {host}",
        "Monitor DNS traffic for fruther beaconing"
    ]     
    
    mitre_chain = []

    if any ("Failed logins" in f for f in findings):
        mitre_chain.append("✅ Initial Access ⮕ T1110 (Brute Force)")
    if any("DNS heartbeat" in f for f in findings):
        mitre_chain.append("✅ C2 Channel     ⮕ T1071 (Beaconing)")
    if any("Suspicious .exe" in f for f in findings):
        mitre_chain.append("✅ Execution      ⮕ T1059 (Malicious Upload)")

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_id = f"CTI-INC-{datetime.datetime.now().strftime('%Y%m%d%H%M')}"

    # --- Step 3: Conditional Section Logic (Refined) ---
    formatted_mitre = "\n".join(mitre_chain)

    formatted_recs = "\n".join([f"- [ ] {r}" for r in recs])
    dynamic_analysis = ""
    if any("Failed logins" in f for f in findings):
        dynamic_analysis += "✅ [INITIAL ACCESS]: Multiple failed login attempts observed (T1110).\n"
    if any("DNS heartbeat" in f for f in findings):
        dynamic_analysis += "✅ [COMMAND & CONTROL]: Repeated DNS beaconing detected (T1071).\n"
    if any("Suspicious .exe" in f for f in findings):
        dynamic_analysis += "✅ [EXECUTION]: Suspicious file execution observed (T1059).\n"

    # Step 4: Final Template with Dynamic Variables
    report_template = f"""
================================================================================
🛡️  AUTOMATED CTI INCIDENT REPORT | {report_id}
================================================================================
DATE/TIME     : {timestamp}
TARGET HOST   : {host}
RISK SCORE    : {score} / 20
SEVERITY      : {priority}
STATUS        : INVESTIGATION COMPLETE - ACTION REQUIRED
--------------------------------------------------------------------------------

1. EXECUTIVE SUMMARY
The CTI Engine has confirmed a {priority} breach on {host}. 
The current threat score ({score}) indicates a possible compromise.

2. AUTOMATED ATTACK ANALYSIS
{dynamic_analysis if dynamic_analysis else "No specific tactical patterns identified."}

3. RECONSTRUCTED ATTACK CHAIN (MITRE ATT&CK)
{formatted_mitre if formatted_mitre else "No MITRE techniques identified."}

4. FORENSIC FINDINGS (AUTO-VERIFIED)
{chr(10).join([f" [!] {finding}" for finding in findings])}

5. INDICATORS OF COMPROMISE (IOCs)
- Attacker IP   : {attacker_ip}
- C2 Domain     : {c2_domain}
- Target Host   : {host}

6. RECOMMENDED SOAR ACTIONS
{formatted_recs}

--------------------------------------------------------------------------------
GENERATED BY: VENOM-SOAR-ENGINE V3.7 (AUTOMATED)
================================================================================
"""
    filename = f"reports/AUTOMATED_REPORT_{host}.txt"
    with open(filename, "w") as f:
        f.write(report_template)
    
    print(f"🚀 [SUCCESS] Automated CTI Report generated: {filename}")

if __name__ == "__main__":
    # Simulated Payload (Real-world incident simulation)
    incident_payload = {
        'host': 'host1',
        'score': 14,
        'priority': '🔴 CRITICAL',
        'attacker_ip': '103.45.67.89',
        'c2_domain': 'evil-c2.com',
        'rule_triggered': 'Aggregated_KillChain_Correlation',
        'mitre_map': {
            'Initial Access': 'T1110 (Brute Force)',
            'C2 Channel': 'T1071 (Beaconing)',
            'Execution': 'T1059 (Malicious Upload)'
        },
        'findings': [
            "10+ Failed logins detected",
            "DNS heartbeat to evil-c2.com verified",
            "Suspicious .exe file detected in /tmp"
        ]
    }
    generate_automated_cti_report(incident_payload)